### ISSUE TITLE
Editing a walk puts all facilities on it

### ISSUE THREAD

**Issue by pmj109** [StefanMdvs/kids-love-walking#2]
If you create a walk with only some facilities (e.g. Car Park and Toilet) and save it, then it is initially created with just the facilities selected. However, if you then edit the walk, the facilities selector has all facilities selected, and if you save your changes then the walk will be saved with all facilities.

**Comment by StefanMdvs** [comment]
Thank you, I loved the challenge :)

**Comment by StefanMdvs** [comment]
Thank you, fixed that plus another issue :)

În mie., 3 mai 2023 la 11:17, pmj109 ***@***.***> a scris:
